trajectory_planner:
  ros__parameters:
    odom_topic: "/odom"
    map_topic: "/map"
    scan_topic: "/scan"
    initial_pose_topic: "/initialpose"
    car_length: 0.45
    max_steer: 0.8
    sample_goal_prob: 0.05
    neighbor_type: "num" # num or radius
    neighbor_num: 10
    neighbor_radius: 2.0
    num_iters: 100
    dist_limit: False
    discretize_path_progress: True
    progress_discretization_dist: 0.5
    discretize_path_publish: True
    publish_discretization_dist: 0.5
    check_discretization_dist: 0.1
trajectory_follower:
  ros__parameters:
    odom_topic: "/odom"
    drive_topic: "/drive"
